name: Label Semaphore
branding:
  icon: arrow-right-circle
  color: gray-dark
description: |
  Update img in remote repo with correct tag based on labeled pull request; scripts prevent duplicate labels on pull requests

inputs:
  debug-mode:
    description: Set to true for verbose execution when debugging
    required: false
    default: 'false'
  log-level:
    description: The log level to use for the execution
    required: false
    default: 'info'
  log-timestamped:
    description: Set to true in order to enable timestamps on log messages
    required: false
    default: 'true'
  github-token:
    description: The token to use for the GitHub API and to update the remote repository
    required: true
  pr-label:
    description: The label to use for the semaphore
    required: true
  pr-number:
    description: The current pull request number
    required: true
  argo-repo:
    description: The repository to update with the semaphore version
    required: true
  use-alpha-channel:
    description: Set to true to use the alpha channel for the semaphore
    required: false
    default: 'true'
  argo-path-file:
    description: The path to the file to update in the repository
    required: true
  semaphore-action:
    description: The action to perform on the semaphore
    required: true


runs:
  using: 'docker'
  image: Dockerfile
  env:
    DEBUG_MODE: ${{ inputs.debug-mode }}
    LOG_LEVEL: ${{ inputs.log-level }}
    LOG_TIMESTAMPED: ${{ inputs.log-timestamped }}
    PR_LABEL: ${{ inputs.pr-label }}
    PR_NUMBER: ${{ inputs.pr-number }}
    ARGO_REPO: ${{ inputs.argo-repo }}
    PR_USE_ALPHA_CHANNEL: ${{ inputs.use-alpha-channel }}
    ARGO_REVISION_PATH: ${{ inputs.argo-path-file }}
    SEMAPHORE_ACTION: ${{ inputs.semaphore-action }}
